"""Initial schema with all models

Revision ID: 1673188ff217
Revises: 
Create Date: 2025-12-19 22:39:53.261225+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1673188ff217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('policyholder_name', sa.String(length=255), nullable=False),
    sa.Column('policyholder_email', sa.String(length=255), nullable=True),
    sa.Column('policy_type', sa.String(length=50), nullable=False, comment='auto, property, liability'),
    sa.Column('coverage_limit', sa.Float(), nullable=False, comment='Maximum coverage amount'),
    sa.Column('deductible', sa.Float(), nullable=False, comment='Deductible amount'),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('coverage_details', sa.JSON(), nullable=True, comment='Detailed coverage information for RAG'),
    sa.Column('document_url', sa.String(length=500), nullable=True, comment='URL to policy document in storage'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_policies_created_at'), 'policies', ['created_at'], unique=False)
    op.create_index(op.f('ix_policies_effective_date'), 'policies', ['effective_date'], unique=False)
    op.create_index(op.f('ix_policies_expiration_date'), 'policies', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_policies_is_active'), 'policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_index(op.f('ix_policies_policy_type'), 'policies', ['policy_type'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.Enum('ADMIN', 'ADJUSTER', 'INVESTIGATOR', 'VIEWER', 'API_USER', name='roletype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active users can log in'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email verification status'),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='Account locked until this time after too many failed logins'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('claims',
    sa.Column('claim_number', sa.String(length=50), nullable=False, comment='Human-readable claim number (e.g., CLM-2024-001234)'),
    sa.Column('claim_type', sa.Enum('AUTO', 'PROPERTY', 'LIABILITY', name='claimtype'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'PROCESSING', 'UNDER_REVIEW', 'INVESTIGATING', 'APPROVED', 'DENIED', 'SETTLED', 'CLOSED', name='claimstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='claimpriority'), nullable=False),
    sa.Column('claimant_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False, comment='Policy this claim is filed under'),
    sa.Column('assigned_adjuster_id', sa.UUID(), nullable=True, comment='Adjuster assigned to review this claim'),
    sa.Column('incident_date', sa.DateTime(), nullable=False, comment='When the incident occurred'),
    sa.Column('incident_location', sa.String(length=500), nullable=True, comment='Where the incident happened'),
    sa.Column('description', sa.Text(), nullable=False, comment="Claimant's description of what happened"),
    sa.Column('estimated_damage', sa.Float(), nullable=False, comment="Claimant's initial damage estimate"),
    sa.Column('approved_amount', sa.Float(), nullable=True, comment='Final approved settlement amount'),
    sa.Column('deductible', sa.Float(), nullable=True, comment='Deductible amount from policy'),
    sa.Column('fraud_score', sa.Float(), nullable=True, comment='Fraud probability (0.0 to 1.0) from ML model'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment="System's confidence in automated decision"),
    sa.Column('workflow_state', sa.JSON(), nullable=True, comment='LangGraph workflow state (serialized)'),
    sa.Column('auto_approved', sa.Boolean(), nullable=False, comment='Whether claim was auto-approved by system'),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('claim_metadata', sa.JSON(), nullable=True, comment='Additional flexible data storage'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_adjuster_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_claims_adjuster_status', 'claims', ['assigned_adjuster_id', 'status'], unique=False)
    op.create_index(op.f('ix_claims_assigned_adjuster_id'), 'claims', ['assigned_adjuster_id'], unique=False)
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_claimant_id'), 'claims', ['claimant_id'], unique=False)
    op.create_index('ix_claims_claimant_status', 'claims', ['claimant_id', 'status'], unique=False)
    op.create_index(op.f('ix_claims_created_at'), 'claims', ['created_at'], unique=False)
    op.create_index(op.f('ix_claims_deleted_at'), 'claims', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_claims_fraud_score'), 'claims', ['fraud_score'], unique=False)
    op.create_index('ix_claims_fraud_score_status', 'claims', ['fraud_score', 'status'], unique=False)
    op.create_index(op.f('ix_claims_incident_date'), 'claims', ['incident_date'], unique=False)
    op.create_index(op.f('ix_claims_is_deleted'), 'claims', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_claims_policy_id'), 'claims', ['policy_id'], unique=False)
    op.create_index(op.f('ix_claims_priority'), 'claims', ['priority'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_index('ix_claims_status_submitted', 'claims', ['status', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_claims_submitted_at'), 'claims', ['submitted_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('damage_assessments',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='URL to image/video in storage'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='image or video'),
    sa.Column('damage_type', sa.Enum('SCRATCH', 'DENT', 'CRACK', 'BROKEN', 'SHATTERED', 'CRUSHED', 'BURNED', 'WATER_DAMAGE', 'UNKNOWN', name='damagetype'), nullable=True),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'MAJOR', 'TOTAL_LOSS', name='damageseverity'), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True, comment='0-100 scale, where 100 is total loss'),
    sa.Column('affected_areas', sa.JSON(), nullable=True, comment='List of damaged parts/areas'),
    sa.Column('estimated_cost_min', sa.Float(), nullable=True),
    sa.Column('estimated_cost_max', sa.Float(), nullable=True),
    sa.Column('ai_response', sa.JSON(), nullable=True, comment='Complete response from OpenAI Vision API'),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='e.g., gpt-4o-mini'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment="AI's confidence in assessment (0-1)"),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('human_override', sa.Boolean(), nullable=True, comment='True if adjuster changed AI assessment'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_damage_assessments_claim_id'), 'damage_assessments', ['claim_id'], unique=False)
    op.create_index(op.f('ix_damage_assessments_created_at'), 'damage_assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_damage_assessments_damage_type'), 'damage_assessments', ['damage_type'], unique=False)
    op.create_index(op.f('ix_damage_assessments_severity'), 'damage_assessments', ['severity'], unique=False)
    op.create_table('fraud_scores',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False, comment='Composite fraud probability (0.0 to 1.0)'),
    sa.Column('ml_model_score', sa.Float(), nullable=True, comment='XGBoost/RandomForest prediction'),
    sa.Column('graph_network_score', sa.Float(), nullable=True, comment='Neo4j graph analysis score'),
    sa.Column('pattern_matching_score', sa.Float(), nullable=True, comment='Rule-based pattern detection'),
    sa.Column('fraud_flags', sa.JSON(), nullable=True, comment='List of suspicious patterns detected'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='low, medium, high, critical'),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='Version of fraud detection model used'),
    sa.Column('feature_importance', sa.JSON(), nullable=True, comment='Which features contributed most to score'),
    sa.Column('fraud_network_id', sa.String(length=100), nullable=True, comment='ID of fraud ring/network in Neo4j'),
    sa.Column('network_connections', sa.JSON(), nullable=True, comment='Related claimants, vehicles, shops'),
    sa.Column('requires_investigation', sa.Boolean(), nullable=False),
    sa.Column('investigated', sa.Boolean(), nullable=False),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('confirmed_fraud', sa.Boolean(), nullable=True, comment='Human confirmation of fraud'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_fraud_scores_claim_id'), 'fraud_scores', ['claim_id'], unique=False)
    op.create_index(op.f('ix_fraud_scores_created_at'), 'fraud_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_scores_fraud_score'), 'fraud_scores', ['fraud_score'], unique=False)
    op.create_index(op.f('ix_fraud_scores_requires_investigation'), 'fraud_scores', ['requires_investigation'], unique=False)
    op.create_index(op.f('ix_fraud_scores_risk_level'), 'fraud_scores', ['risk_level'], unique=False)
    op.create_table('settlements',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False, comment='Final approved settlement'),
    sa.Column('deductible_applied', sa.Float(), nullable=False),
    sa.Column('net_payment', sa.Float(), nullable=False, comment='Amount actually paid to claimant'),
    sa.Column('settlement_letter', sa.Text(), nullable=True, comment='AI-generated explanation letter'),
    sa.Column('letter_url', sa.String(length=500), nullable=True, comment='URL to PDF letter in storage'),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_settlements_claim_id'), 'settlements', ['claim_id'], unique=True)
    op.create_index(op.f('ix_settlements_created_at'), 'settlements', ['created_at'], unique=False)
    op.create_table('workflow_states',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False, comment='Which workflow node was executed'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Order of execution in workflow'),
    sa.Column('input_state', sa.JSON(), nullable=True, comment='State when entering this node'),
    sa.Column('output_state', sa.JSON(), nullable=True, comment='State when exiting this node'),
    sa.Column('decision', sa.String(length=100), nullable=True, comment='Decision made by this node'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='Why this decision was made (from LLM)'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='How long this node took to execute'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_workflow_states_claim_id'), 'workflow_states', ['claim_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_created_at'), 'workflow_states', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_states_created_at'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_claim_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_index(op.f('ix_settlements_created_at'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_claim_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_fraud_scores_risk_level'), table_name='fraud_scores')
    op.drop_index(op.f('ix_fraud_scores_requires_investigation'), table_name='fraud_scores')
    op.drop_index(op.f('ix_fraud_scores_fraud_score'), table_name='fraud_scores')
    op.drop_index(op.f('ix_fraud_scores_created_at'), table_name='fraud_scores')
    op.drop_index(op.f('ix_fraud_scores_claim_id'), table_name='fraud_scores')
    op.drop_table('fraud_scores')
    op.drop_index(op.f('ix_damage_assessments_severity'), table_name='damage_assessments')
    op.drop_index(op.f('ix_damage_assessments_damage_type'), table_name='damage_assessments')
    op.drop_index(op.f('ix_damage_assessments_created_at'), table_name='damage_assessments')
    op.drop_index(op.f('ix_damage_assessments_claim_id'), table_name='damage_assessments')
    op.drop_table('damage_assessments')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_claims_submitted_at'), table_name='claims')
    op.drop_index('ix_claims_status_submitted', table_name='claims')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_priority'), table_name='claims')
    op.drop_index(op.f('ix_claims_policy_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_is_deleted'), table_name='claims')
    op.drop_index(op.f('ix_claims_incident_date'), table_name='claims')
    op.drop_index('ix_claims_fraud_score_status', table_name='claims')
    op.drop_index(op.f('ix_claims_fraud_score'), table_name='claims')
    op.drop_index(op.f('ix_claims_deleted_at'), table_name='claims')
    op.drop_index(op.f('ix_claims_created_at'), table_name='claims')
    op.drop_index('ix_claims_claimant_status', table_name='claims')
    op.drop_index(op.f('ix_claims_claimant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_index(op.f('ix_claims_assigned_adjuster_id'), table_name='claims')
    op.drop_index('ix_claims_adjuster_status', table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_policies_policy_type'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_is_active'), table_name='policies')
    op.drop_index(op.f('ix_policies_expiration_date'), table_name='policies')
    op.drop_index(op.f('ix_policies_effective_date'), table_name='policies')
    op.drop_index(op.f('ix_policies_created_at'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
