"""Make claimant_id nullable for historical data

Revision ID: 350abd326819
Revises: 1673188ff217
Create Date: 2025-12-19 22:48:38.754412+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350abd326819'
down_revision = '1673188ff217'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'claimant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'claims', ['id'])
    op.create_unique_constraint(None, 'damage_assessments', ['id'])
    op.create_unique_constraint(None, 'fraud_scores', ['id'])
    op.create_unique_constraint(None, 'policies', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'settlements', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'workflow_states', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_states', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'settlements', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'policies', type_='unique')
    op.drop_constraint(None, 'fraud_scores', type_='unique')
    op.drop_constraint(None, 'damage_assessments', type_='unique')
    op.drop_constraint(None, 'claims', type_='unique')
    op.alter_column('claims', 'claimant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
